dist: trusty
language : node_js
node_js : "stable"
before_script:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - gulp browserify
script : karma start karma.conf.js

after_script: cat coverage/**/*lcov.info | ./node_modules/.bin/coveralls
